language: cpp
compiler: 
    - gcc
notifications:
    email: false
env:
    matrix:
        - JULIAVERSION="juliareleases"
        - JULIAVERSION="julianightlies"
before_install:
    - sudo add-apt-repository ppa:staticfloat/julia-deps -y
    - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
    - sudo apt-get update -qq -y
    - sudo apt-get install git julia imagemagick -y
    - git config --global user.name "Travis User"
    - git config --global user.email "travis@example.net"
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
    - julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir("Images"))`); Pkg.pin("Images"); Pkg.resolve()'
    - if [ $JULIAVERSION = "julianightlies" ]; then julia --code-coverage tests/runtests.jl; fi
    - if [ $JULIAVERSION = "juliarelease" ]; then julia tests/test.jl; fi
    - if [ $JULIAVERSION = "julianightlies" ]; then julia -e 'Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'; fi

